### ISSUE TITLE
Does not luanch when JAVA 10 is installed

### ISSUE THREAD

**Issue by djkrimson** [tvrenamer/tvrenamer#324]
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

**Comment by htr3n** [comment]
Hi, it could be a problem with JavaAppLauncher checking Java runtime version. Java 9 and 10 could cause problems. In case you are interested in rebuilding a working app, you can use `javapackager` (please see some hints [here](https://github.com/htr3n/tvrenamer/blob/master/README.md) that might also work for platforms other than macOS).

**Comment by bdmorin** [comment]
```
> java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

> java -jar tvrenamer.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/Users/bdmorin/Downloads/TVRenamer-0.8.app/Contents/Java/tvrenamer.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
***WARNING: Display must be created on main thread due to Cocoa restrictions.
Exception in thread "main" org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.tvrenamer.view.UIStarter.init(UIStarter.java:109)
	at org.tvrenamer.view.UIStarter.run(UIStarter.java:520)
	at org.tvrenamer.controller.Launcher.main(Launcher.java:50)
```

**Comment by htr3n** [comment]
Maybe try with `-XstartOnFirstThread`. This should be set when packaging the `tvrenamer.jar` but perhaps you can give a try at command line.

`java --XstartOnFirstThread -jar tvrenamer.jar`

**Comment by bdmorin** [comment]
Yep, that did it, at least for me.

**Comment by vipuldelwadia** [comment]
The old `.exe` and `.app` came from an Ant build that stopped working on modern JDKs. 1.0 replaces both. The macOS `.dmg` and the Windows portable zip each carry their own Java 21 runtime, so there is no separate Java to install and nothing to mismatch. The `.dmg` is signed and notarised.

Download: https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0

Closing. If 1.0 still fails to start, please reopen with the output from running it in a terminal.
