### ISSUE TITLE
v1.0b4 Not working correctly MAC

### ISSUE THREAD

**Issue by Wiggum72** [tvrenamer/tvrenamer#397]
v1.0b4 Doesn't seem to be opening properly on Mac. It puts the icon on my bar but does not pop up the GUI. The icon also goes away after a few seconds.

**Comment by Wiggum72** [comment]
This is my debugging info if it helps any 

---- Debugging information ----
message             : No such field org.tvrenamer.model.UserPreferences.proxy
field               : proxy
class               : org.tvrenamer.model.UserPreferences
required-type       : org.tvrenamer.model.UserPreferences
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /preferences/proxy
line number         : 6
version             : not available
-------------------------------
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.handleUnknownField(AbstractReflectionConverter.java:524)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:375)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1094)
	at org.tvrenamer.controller.UserPreferencesPersistence.retrieve(UserPreferencesPersistence.java:58)
	at org.tvrenamer.model.UserPreferences.load(UserPreferences.java:184)
	at org.tvrenamer.model.UserPreferences.<clinit>(UserPreferences.java:21)
	... 3 more
2019-12-14 07:36:31.060 TVRenamer[51606:8898361] TVRenamer:Failed to launch JVM

**Comment by vipuldelwadia** [comment]
The old `.exe` and `.app` came from an Ant build that stopped working on modern JDKs. 1.0 replaces both. The macOS `.dmg` and the Windows portable zip each carry their own Java 21 runtime, so there is no separate Java to install and nothing to mismatch. The `.dmg` is signed and notarised.

Download: https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0

Closing. If 1.0 still fails to start, please reopen with the output from running it in a terminal.
