### ISSUE TITLE
Bug - Doesn't work

### ISSUE THREAD

**Issue by P4R4NORM4L** [tvrenamer/tvrenamer#401]
`[Fatal Error] :1:65: Element type "body" must be followed by either attribute specifications, ">" or "/>".
2020/02/10 07:46:05,464 WARN TheTVDBProvider#readShowsFromInputSource Error parsing XML
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 65; Element type "body" must be followed by either attribute specifications, ">" or "/>".
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.tvrenamer.controller.TheTVDBProvider.readShowsFromInputSource(TheTVDBProvider.java:156)
        at org.tvrenamer.controller.TheTVDBProvider.getShowOptions(TheTVDBProvider.java:180)
        at org.tvrenamer.model.ShowStore.lambda$downloadShow$4(ShowStore.java:198)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

2020/02/10 07:46:05,478 WARN TheTVDBProvider#getShowOptions error parsing XML from <html><head><title>301%20Moved%20Permanently</title></head><body%20bgcolor="white"><center><h1>301%20Moved%20Permanently</h1></center><hr><center>CloudFront</center></body></html> for series Homeland.
org.tvrenamer.model.TVRenamerIOException: Error parsing XML
        at org.tvrenamer.controller.TheTVDBProvider.readShowsFromInputSource(TheTVDBProvider.java:161)
        at org.tvrenamer.controller.TheTVDBProvider.getShowOptions(TheTVDBProvider.java:180)
        at org.tvrenamer.model.ShowStore.lambda$downloadShow$4(ShowStore.java:198)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 65; Element type "body" must be followed by either attribute specifications, ">" or "/>".
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.tvrenamer.controller.TheTVDBProvider.readShowsFromInputSource(TheTVDBProvider.java:156)
        ... 6 more

2020/02/10 07:46:05,480 WARN FailedShow#logShowFailure failed to get show for Homeland.
org.tvrenamer.model.TVRenamerIOException: error parsing XML from <html><head><title>301%20Moved%20Permanently</title></head><body%20bgcolor="white"><center><h1>301%20Moved%20Permanently</h1></center><hr><center>CloudFront</center></body></html> for series Homeland.
        at org.tvrenamer.controller.TheTVDBProvider.getShowOptions(TheTVDBProvider.java:189)
        at org.tvrenamer.model.ShowStore.lambda$downloadShow$4(ShowStore.java:198)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.tvrenamer.model.TVRenamerIOException: Error parsing XML
        at org.tvrenamer.controller.TheTVDBProvider.readShowsFromInputSource(TheTVDBProvider.java:161)
        at org.tvrenamer.controller.TheTVDBProvider.getShowOptions(TheTVDBProvider.java:180)
        ... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 65; Element type "body" must be followed by either attribute specifications, ">" or "/>".
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.tvrenamer.controller.TheTVDBProvider.readShowsFromInputSource(TheTVDBProvider.java:156)
        ... 6 more
`

**Comment by StephKoenig** [comment]
A new version was released a while back by vipuldelwadia who kindly compiled all the pending patches and updated to the new tvdb api format
https://github.com/tvrenamer/tvrenamer/releases

**Comment by P4R4NORM4L** [comment]
Current Version Bug
`java -jar "TVRenamer-1.0b4-win64 (1).exe"
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM
        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
        at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
        at org.tvrenamer.view.UIStarter.<init>(UIStarter.java:249)
        at org.tvrenamer.controller.Launcher.main(Launcher.java:49)`

**Comment by StephKoenig** [comment]
> ava.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source) at

Theres a clue to one of the issues... Either try the 32bit version of TVRenamer or install the 64 bit JVM. Google Java 64 bit)... I'd try the 32 bit version of TVRenamer it's easier...

**Comment by vipuldelwadia** [comment]
The old `.exe` and `.app` came from an Ant build that stopped working on modern JDKs. 1.0 replaces both. The macOS `.dmg` and the Windows portable zip each carry their own Java 21 runtime, so there is no separate Java to install and nothing to mismatch. The `.dmg` is signed and notarised.

Download: https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0

Closing. If 1.0 still fails to start, please reopen with the output from running it in a terminal.
