### ISSUE TITLE
Refuses to start on windows 10

### ISSUE THREAD

**Issue by drpain** [tvrenamer/tvrenamer#410]
When I try and run the application by double clicking it nothing happens. 

Java version:
```shell
PS C:\Users\Rudi\Downloads> java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```

When I run it in debug mode, I get the following error message:
```shell
PS C:\Users\Rudi\Downloads> java -jar .\TVRenamer-0.8-win64.exe
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.tvrenamer.model.EpisodeDb.<init>(EpisodeDb.java:21)
        at org.tvrenamer.view.UIStarter.<init>(UIStarter.java:99)
        at org.tvrenamer.controller.Launcher.main(Launcher.java:49)
Caused by: com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field org.tvrenamer.model.UserPreferences.deleteRowAfterMove
---- Debugging information ----
message             : No such field org.tvrenamer.model.UserPreferences.deleteRowAfterMove
field               : deleteRowAfterMove
class               : org.tvrenamer.model.UserPreferences
required-type       : org.tvrenamer.model.UserPreferences
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /preferences/deleteRowAfterMove
line number         : 8
version             : not available
-------------------------------
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.handleUnknownField(AbstractReflectionConverter.java:524)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:375)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1094)
        at org.tvrenamer.controller.UserPreferencesPersistence.retrieve(UserPreferencesPersistence.java:56)
        at org.tvrenamer.model.UserPreferences.load(UserPreferences.java:153)
        at org.tvrenamer.model.UserPreferences.<clinit>(UserPreferences.java:35)
```

Any help would be appreciated! I really love the application, but haven't been able to use it in some time

**Comment by drpain** [comment]
The beta version does work, but it's not the one linked on the download latest page. And isn't in master I imagine. 

https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0b4

**Comment by eprenamer** [comment]
I reproduced the behavior and I'm really not sure what's going on.  In the code base that the version is built from, the error doesn't happen, and certainly the field that it's complaining about does exist.

I haven't done the packaging process in over two years, but I will try to get back to it and see what's going on. 

In the mean time, maybe you can help me a bit.  I do have a Windows 10 box, but I'm more of a Mac guy.  How exactly did you see that backtrace on Windows?  When I try to run it, it just fails to run, silently.

**Comment by vipuldelwadia** [comment]
The old `.exe` and `.app` came from an Ant build that stopped working on modern JDKs. 1.0 replaces both. The macOS `.dmg` and the Windows portable zip each carry their own Java 21 runtime, so there is no separate Java to install and nothing to mismatch. The `.dmg` is signed and notarised.

Download: https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0

Closing. If 1.0 still fails to start, please reopen with the output from running it in a terminal.
