### ISSUE TITLE
Won't Open

### ISSUE THREAD

**Issue by daduber** [tvrenamer/tvrenamer#413]
Uninstalled Older Java and reinstalled now doesn't even open in windows 10

**Comment by StephKoenig** [comment]
Works fine here.. 

If it helps I'm on W10 19043 21H1 using Java 64bit 1.8.0 291-b10.

**Comment by Forceu** [comment]
Same here, doesn't open for me anymore with openjdk 16.0.1

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:832)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:364)
	at org.tvrenamer.controller.UserPreferencesPersistence.<clinit>(UserPreferencesPersistence.java:21)
	at org.tvrenamer.model.UserPreferences.load(UserPreferences.java:153)
	at org.tvrenamer.model.UserPreferences.<clinit>(UserPreferences.java:35)
	at org.tvrenamer.model.EpisodeDb.<init>(EpisodeDb.java:21)
	at org.tvrenamer.view.UIStarter.<init>(UIStarter.java:99)
	at org.tvrenamer.controller.Launcher.main(Launcher.java:49)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @4434095f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	... 12 more
```

**Comment by vipuldelwadia** [comment]
The old `.exe` and `.app` came from an Ant build that stopped working on modern JDKs. 1.0 replaces both. The macOS `.dmg` and the Windows portable zip each carry their own Java 21 runtime, so there is no separate Java to install and nothing to mismatch. The `.dmg` is signed and notarised.

Download: https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0

Closing. If 1.0 still fails to start, please reopen with the output from running it in a terminal.
