### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. 

### ISSUE THREAD

**Issue by Ph1L82** [tvrenamer/tvrenamer#422]
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	22.0.0
Codename:	Sikaris

JAVA_HOME=/usr/lib/jvm/java-8-openjd

java -version                                                                                                                                                                         ✔ 
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)

Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi-gtk-4332 in java.library.path
	no swt-pi-gtk in java.library.path
	/home/ph1l/.swt/lib/linux/x86_64/libswt-pi-gtk-4332.so: libgtk-x11-2.0.so.0: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
	Can't load library: /home/ph1l/.swt/lib/linux/x86_64/libswt-pi-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at org.tvrenamer.view.UIStarter.init(UIStarter.java:108)
	at org.tvrenamer.view.UIStarter.run(UIStarter.java:520)
	at org.tvrenamer.controller.Launcher.main(Launcher.java:50

**Comment by vipuldelwadia** [comment]
The SWT native library is matched to the platform at build time, and CI now launches the GUI on macOS, Windows and Linux on every build to catch exactly this. The 1.0 bundles also carry their own Java 21 runtime, so there is no mismatch with a separately installed Java.

Release: https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0

Closing. Please reopen with the terminal output if it still happens on 1.0.
