### ISSUE TITLE
TVRenamer-0.7 will not start

### ISSUE THREAD

**Issue by vaderj** [tvrenamer/tvrenamer#97]
Platform: Win10 x64, AMD 8-core, 32GB RAM
********************************
java -version
-----------------
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

*******************************
java.exe -jar TVRenamer-0.7-win64.exe
--------------------------------------------------------
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/code/tvrenamer/view/UIStarter : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by vipuldelwadia** [comment]
It looks like you have older versions of Java installed on your computer, try running the Java uninstall tool and removing the older versions: https://java.com/en/download/faq/uninstaller_toolinfo.xml

**Comment by vipuldelwadia** [comment]
Closing due to inactivity, please reopen if this is still an issue.
